//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "Bars.xaml.h"
#include "PhotoEditor.xaml.h"
#include "TransactionFlowControl.xaml.h"
#include "Triangle.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "Bars.g.hpp"
#include "PhotoEditor.g.hpp"
#include "TransactionFlowControl.g.hpp"
#include "Triangle.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_RenderType(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->RenderType);
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_TransactionFlowItems(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->TransactionFlowItems;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Text(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Text;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_SubHeader(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->SubHeader;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Header(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Header;
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_RenderType(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->RenderType = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_TransactionFlowItems(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->TransactionFlowItems = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Text(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Text = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_SubHeader(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->SubHeader = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Header(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Header = safe_cast<TValue^>(value);
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    unsigned int flags;
};

const TypeInfo TypeInfos[] = 
{
    //   0
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   1
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   2
    L"System.Enum", L"",
    nullptr, nullptr, nullptr, nullptr,
    4, // System.ValueType
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    //   3
    L"sggraphs.Bars", L"",
    &ActivateType<::sggraphs::Bars>, nullptr, nullptr, nullptr,
    9, // Windows.UI.Xaml.Controls.UserControl
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   4
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    //   5
    L"sggraphs.Triangle", L"",
    &ActivateType<::sggraphs::Triangle>, nullptr, nullptr, nullptr,
    9, // Windows.UI.Xaml.Controls.UserControl
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   6
    L"sggraphs.PhotoEditor", L"",
    &ActivateType<::sggraphs::PhotoEditor>, nullptr, nullptr, nullptr,
    9, // Windows.UI.Xaml.Controls.UserControl
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   7
    L"sggraphs.TransactionFlowItem", L"",
    &ActivateType<::sggraphs::TransactionFlowItem>, nullptr, nullptr, nullptr,
    0, // Object
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   8
    L"sggraphs.TransactionFlowControl", L"",
    &ActivateType<::sggraphs::TransactionFlowControl>, nullptr, nullptr, nullptr,
    9, // Windows.UI.Xaml.Controls.UserControl
    4, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   9
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    5, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  10
    L"sggraphs.TransactionFlowItemRenderType", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::sggraphs::TransactionFlowItemRenderType>,
    2, // System.Enum
    5, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  11
    L"Windows.Foundation.Collections.IVector`1<sggraphs.TransactionFlowItem>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::sggraphs::TransactionFlowItem^>, ::sggraphs::TransactionFlowItem^>, nullptr, nullptr,
    -1,
    5, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    5, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_None,
};

const UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      0,   //   6
      2,   //   7
      2,   //   8
      2,   //   9
      2,   //  10
      2,   //  11
      3,   //  12
      3,   //  13
      4,   //  14
      4,   //  15
      4,   //  16
      5,   //  17
      6,   //  18
      6,   //  19
      6,   //  20
      7,   //  21
      7,   //  22
      7,   //  23
      7,   //  24
      7,   //  25
      7,   //  26
      7,   //  27
      7,   //  28
      8,   //  29
      8,   //  30
      8,   //  31
      9,   //  32
      9,   //  33
      9,   //  34
      9,   //  35
      9,   //  36
     10,   //  37
     10,   //  38
     11,   //  39
     11,   //  40
     11,   //  41
     11,   //  42
     11,   //  43
     11,   //  44
     11,   //  45
     11,   //  46
     11,   //  47
     11,   //  48
     11,   //  49
     11,   //  50
     11,   //  51
     11,   //  52
     11,   //  53
     11,   //  54
     11,   //  55
     11,   //  56
     11,   //  57
     11,   //  58
     11,   //  59
     11,   //  60
     11,   //  61
     11,   //  62
     11,   //  63
     11,   //  64
     11,   //  65
     11,   //  66
     11,   //  67
     11,   //  68
     11,   //  69
     11,   //  70
     12,   //  71
};

struct EnumValueInfo
{
    PCWSTR name;
    int eValue;
};

const EnumValueInfo EnumValues[] =
{ 
    L"ForwardConnector", (int) ::sggraphs::TransactionFlowItemRenderType::ForwardConnector,
    L"StartNode", (int) ::sggraphs::TransactionFlowItemRenderType::StartNode,
    L"EndNode", (int) ::sggraphs::TransactionFlowItemRenderType::EndNode,
    L"Process", (int) ::sggraphs::TransactionFlowItemRenderType::Process,
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - sggraphs.TransactionFlowItem.Text
    L"Text",
    &GetReferenceTypeMember_Text<::sggraphs::TransactionFlowItem>,
    &SetReferenceTypeMember_Text<::sggraphs::TransactionFlowItem, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   1 - sggraphs.TransactionFlowItem.SubHeader
    L"SubHeader",
    &GetReferenceTypeMember_SubHeader<::sggraphs::TransactionFlowItem>,
    &SetReferenceTypeMember_SubHeader<::sggraphs::TransactionFlowItem, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   2 - sggraphs.TransactionFlowItem.Header
    L"Header",
    &GetReferenceTypeMember_Header<::sggraphs::TransactionFlowItem>,
    &SetReferenceTypeMember_Header<::sggraphs::TransactionFlowItem, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   3 - sggraphs.TransactionFlowItem.RenderType
    L"RenderType",
    &GetValueTypeMember_RenderType<::sggraphs::TransactionFlowItem, ::sggraphs::TransactionFlowItemRenderType>,
    &SetEnumMember_RenderType<::sggraphs::TransactionFlowItem, ::sggraphs::TransactionFlowItemRenderType>,
    10, // sggraphs.TransactionFlowItemRenderType
    -1,
    false, false, false,
    //   4 - sggraphs.TransactionFlowControl.TransactionFlowItems
    L"TransactionFlowItems",
    &GetReferenceTypeMember_TransactionFlowItems<::sggraphs::TransactionFlowControl>,
    &SetReferenceTypeMember_TransactionFlowItems<::sggraphs::TransactionFlowControl, ::Windows::Foundation::Collections::IVector<::sggraphs::TransactionFlowItem^>>,
    11, // Windows.Foundation.Collections.IVector`1<sggraphs.TransactionFlowItem>
    -1,
    false, false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}

const TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    auto typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

const MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    auto lastDotIndex = longMemberName->Length();
    while (true)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            const TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
        if (lastDotIndex == 0)
        {
            break;
        }
        lastDotIndex--;
    }
    return nullptr;
}

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->flags & TypeInfo_Flags_IsLocalType;
        userType->IsReturnTypeStub = pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub;
        userType->IsBindable = pTypeInfo->flags & TypeInfo_Flags_IsBindable;
        userType->IsMarkupExtension = pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension;
        userType->CreateFromStringMethod = nullptr;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; i++)
        {
            userType->AddEnumValue(
                ::Platform::StringReference(EnumValues[i].name),
                ::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

